export const ADD_APPOINTMENT = 'ADD_APPOINTMENT';
export const EDIT_APPOINTMENT = 'EDIT_APPOINTMENT';
export const DELETE_APPOINTMENT = 'DELETE_APPOINTMENT';

export const ADD_BOILERS = 'ADD_BOILERS';
export const EDIT_BOILERS = 'EDIT_BOILERS';
export const DELETE_BOILERS = 'DELETE_BOILERS';