export const GET_BUILDINGS_FETCHING = "GET_BUILDINGS_FETCHING";
export const GET_BUILDINGS_FULFILLED = "GET_BUILDINGS_FULFILLED";
export const GET_BUILDINGS_REJECTED = "GET_BUILDINGS_REJECTED";

export const ADD_BUILDINGS_FETCHING = "ADD_BUILDINGS_FETCHING";
export const ADD_BUILDINGS_FULFILLED = "ADD_BUILDINGS_FULFILLED";
export const ADD_BUILDINGS_REJECTED = "ADD_BUILDINGS_REJECTED";

export const DELETE_BUILDINGS_FETCHING = "DELETE_BUILDINGS_FETCHING";
export const DELETE_BUILDINGS_FULFILLED = "DELETE_BUILDINGS_FULFILLED";
export const DELETE_BUILDINGS_REJECTED = "DELETE_BUILDINGS_REJECTED";
