export const GET_BUILDINGS_PENDING = "GET_BUILDINGS_PENDING";
export const GET_BUILDINGS_FULFILLED = "GET_BUILDINGS_FULFILLED";
export const GET_BUILDINGS_REJECTED = "GET_BUILDINGS_REJECTED";

export const POST_BUILDINGS_PENDING = "POST_BUILDINGS_PENDING";
export const POST_BUILDINGS_FULFILLED = "POST_BUILDINGS_FULFILLED";
export const POST_BUILDINGS_REJECTED = "POST_BUILDINGS_REJECTED";

export const PUT_BUILDINGS_PENDING = "PUT_BUILDING_PENDING";
export const PUT_BUILDINGS_FULFILLED = "PUT_BUILDING_FULFILLED";
export const PUT_BUILDINGS_REJECTED = "PUT_BUILDING_REJECTED";

export const DELETE_BUILDINGS_PENDING = "DELETE_BUILDINGS_PENDING";
export const DELETE_BUILDINGS_FULFILLED = "DELETE_BUILDINGS_FULFILLED";
export const DELETE_BUILDINGS_REJECTED = "DELETE_BUILDINGS_REJECTED";

export const SHOW_MODAL = "SHOW_MODAL";
export const HIDE_MODAL = "HIDE_MODAL";