export const GET_BUILDINGS = "GET_BUILDINGS";

export const ADD_BUILDING = "ADD_BUILDING";

export const DELETE_BUILDING = "DELETE_BUILDING";

export const UPDATE_BUILDING = "UPDATE_BUILDING";

export const SHOW_MODAL = "SHOW_MODAL";
export const HIDE_MODAL = "HIDE_MODAL";
